import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Nav from "../components/navigation/nav";
import TodoForm from "../components/todos/addNewTodo";
import TodoList from "../components/todos/todoList";

export default function Home() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios
      .get("/api/todos")
      .then((res) => {
        setData(res.data.todos);
        setLoading(false);
      })
      .catch((err) => console.log(err));
  }, []);

  // delete function
  const deleteHandler = (id) => {
    axios
      .delete(`/api/todos/${id}`)
      .then((res) => {
        setData(res.data.todos);
        setLoading(false);
      })
      .catch((err) => console.log(err));
  };

  // add Todo function
  const addTodo = (e, formData, setFormData) => {
    e.preventDefault();
    if (formData.title && formData.description) {
      axios
        .post(`/api/todos/`, { formData })
        .then((res) => {
          setData(res.data.todos);
          setLoading(false);
        })
        .catch((err) => console.log(err));
      setFormData({ title: "", description: "" });
    }else{
      alert('please fill out title and description');
    }
  };

  if (loading) return <div>loading...</div>;

  return (
    <div>
      <Head>
        <title>todo app nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* navigation */}
      <Nav />

      <div className="flex flex-col items-center container xl:max-w-screen-xl mx-auto">
        <TodoForm onAdd={addTodo} />

        {/* show todo list */}
        <TodoList data={data} onDeleteTodo={deleteHandler} />
      </div>
    </div>
  );
}
